name: Test Workdlow

on:
  push:

jobs:
  update-labels-config:

    runs-on: ubuntu-latest

    steps:
      - uses: credfeto/action-repo-visibility@master
        id: visibility
        with: 
          repository: ${{ github.repository }}
          token: ${{ github.token }}

      - if: ${{ visibility.is_public }}
        run: echo "Repo is Public"

      - if: ${{ visibility.is_private }}
        run: echo "Repo is PRIVATE"        