name: Test Workflow

on:
  push:

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
      - uses: credfeto/action-repo-visibility@main
        id: visibility
        with: 
          repository: ${{ github.repository }}
          token: ${{ github.token }}

      - if: ${{ steps.visibility.is_public == 'true' }}
        run: echo "Repo is Public"

      - if: ${{ steps.visibility.is_private == 'true' }}
        run: echo "Repo is PRIVATE"        

      - run: echo "Repo is ${{ steps.visibility.status }}"